export const menus = [
    {
        id: 1,
        label: "Home",
        icon: "bx-home-circle",
        link: "/home",
        component: "Home/Index",
        name: "Home",
        user: ['Student','Staff'],
    },
    {
        id: 55,
        label: "Profile",
        icon: "bx-user",
        link: "/students/profile",
        component: "Modules/Student/Profile",
        name: "Home",
        user: ['Student'],
    },
    {
        id: 56,
        label: "Calendar",
        icon: "bx-calendar",
        link: "/appointments/calendar",
        component: "Modules/Appointments/Calendar",
        name: "Home",
        user: ['Staff'],
    },
    {
        id: 2,
        label: "Students",
        icon: "bxs-face",
        link: "/students",
        component: "Modules/Students/Index",
        name: "Modules/Students",
        user: ['Super Administrator','Staff'],
    },
    {
        id: 3,
        label: "Appointments",
        icon: "bx-cabinet",
        link: "/appointments",
        component: "Modules/Appointments/Index",
        name: "Modules/Appointments",
        user: ['Super Administrator','Staff'],
    },
    {
        id: 4,
        label: "Staffs",
        icon: "bxs-user-circle",
        link: "/staffs",
        component: "Modules/Staffs/Index",
        name: "Modules/Staffs",
        user: ['Super Administrator','Staff'],
    },
];